### ISSUE TITLE
Could not find io.kotless:ktor-lang:0.1.6.

### ISSUE THREAD

**Issue by viktor-idenfy** [JetBrains/kotless#103]
Hello, why I keep getting this issue? My gradle file:

`plugins {
    java
    kotlin("jvm") version "1.4.32"
    id("io.kotless") version "0.1.6" apply true
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib"))
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
    implementation(kotlin("stdlib"))
    implementation("io.ktor:ktor-server-core:1.5.3")
    implementation("io.ktor:ktor-server-netty:1.5.3")
    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("io.kotless", "ktor-lang", "0.1.6")
}

tasks.getByName<Test>("test") {
    useJUnitPlatform()
}`

**Comment by TanVD** [comment]
Currently, Kotless is still available in JCenter :)
