### ISSUE TITLE
Deploy to aws error

### ISSUE THREAD

**Issue by MalcolmJRosse** [JetBrains/kotless#22]
`1:14:17 p.m.: Executing task 'deploy'...

> Task :download_terraform
Downloading terraform version 0.11.14 for OS darwin_amd64
Terraform version 0.11.14 for OS darwin_amd64 successfully downloaded

> Task :generate
> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :shadowJar
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Error loading /Users/malcolmjrosse/Desktop/Kotlin-Devs/UpApp-Server/build/kotless-gen/UpApp-Server.tf: Error reading config for aws_cloudwatch_event_target[autowarm_{name}_get]: parse error at 1:38: expected "}" but found invalid sequence "{"

> Task :initialize

Error: Error loading /Users/malcolmjrosse/Desktop/Kotlin-Devs/UpApp-Server/build/kotless-gen/UpApp-Server.tf: Error reading config for aws_cloudwatch_event_target[autowarm_{name}_get]: parse error at 1:38: expected "}" but found invalid sequence "{"

> Task :deploy`

**Comment by TanVD** [comment]
Could you please provide a bit more info? What is the configuration of project? Is code available somewhere, so I can take a look?

**Comment by MalcolmJRosse** [comment]
`import io.kotless.DSLType
import io.kotless.plugin.gradle.dsl.Webapp.Route53
import io.kotless.plugin.gradle.dsl.kotless

plugins {
    java
    kotlin("jvm") version "1.3.61"
    id("io.kotless") version "0.1.2" apply true
}

group = "goup.app"
version = "1.0-GO_UP_APP_SNAPSHOT"

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("io.kotless", "ktor-lang", "0.1.2")
    implementation("net.java.dev.jna", "jna", "5.5.0")
    implementation("com.sun.jna", "jna", "3.0.9")
    testCompile("junit", "junit", "4.12")
}

kotless {
    config {
        bucket = "aws.goup.app"
        prefix = "dev"

        dsl {
            type = DSLType.Ktor
        }

        terraform {
            profile = "mjrosse"
            region = "us-east-1"
        }
    }

    webapp {
        route53 = Route53("aws", "goup.app")

        lambda {
            memoryMb = 128
            timeoutSec = 6

            kotless {
                packages = setOf("goupapp")
            }

        }
    }

}


configure<JavaPluginConvention> {
    sourceCompatibility = JavaVersion.VERSION_1_8
}

tasks {
    compileKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
    compileTestKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
}`

**Comment by TanVD** [comment]
Does your project have a name? I mean, `rootProject.name = "my-name"` in `settings.gradle.kts` :)
