### ISSUE TITLE
(window10) Cannot get property 'kotless' on extra properties extension as it does not exist

### ISSUE THREAD

**Issue by anpaul0615** [JetBrains/kotless#23]
ref : #21  

on linux, `./gradlew` works good but on window10 is not.

how can i build my kotless app on window10?

(capture1 - build.gradle.kts)
![capture1 - build gradle kts](https://user-images.githubusercontent.com/8488507/73329803-46e88480-42a2-11ea-8a07-6aaccb59aac2.png)

(capture2 - gradlew)
![capture2 - gradlew](https://user-images.githubusercontent.com/8488507/73329804-46e88480-42a2-11ea-8845-c2dec9d80bb1.png)

(capture3 - cannot get property kotless)
![capture3 - cannot get property kotless](https://user-images.githubusercontent.com/8488507/73329805-46e88480-42a2-11ea-8315-b6163c8ad650.png)

(capture4 - package cannot be imported)
![capture4 - package cannot be imported](https://user-images.githubusercontent.com/8488507/73329806-46e88480-42a2-11ea-98b7-066f5f469f44.png)

**Comment by TanVD** [comment]
IntelliJ shows that package can not be imported, but does it work from console? It may be a bug in IntelliJ integration with Gradle :)

**Comment by anpaul0615** [comment]
running gradle build is not work also without intellij... :(

(capture5 - running gradle without intellij)
![capture5 - running gradle without intellij](https://user-images.githubusercontent.com/8488507/73625592-e03fde00-4688-11ea-968a-28ec63d03ecb.JPG)

(capture6 - cannot get property kotless without intellij)
![capture6 - cannot get property kotless without intellij](https://user-images.githubusercontent.com/8488507/73625593-e46bfb80-4688-11ea-8b35-ebb9c4443e2a.JPG)

**Comment by TanVD** [comment]
I am not sure, but do you have `kotless { ... }`? As far as I see from screenshot it is not in build.gradle.kts :)
It is mentioned in `Getting Started`: https://github.com/JetBrains/kotless#getting-started :
```
kotless {
    config {
        bucket = "kotless.s3.example.com"
        
        dsl {
            type = DSLType.Kotless
        }

        terraform {
            profile = "example"
            region = "us-east-1"
        }
    }

    webapp {
        route53 = Route53("kotless", "example.com")

        lambda {            
            kotless {
                packages = setOf("io.kotless.examples")
            }
        }
    }
}
```

**Comment by anpaul0615** [comment]
@TanVD 
You're right. It is intellij gradle integration bug.
After update intellij ver2019.3 to ver2019.3.2, it seems to work fine. thankyou :)
