### ISSUE TITLE
Can't start local server

### ISSUE THREAD

**Issue by hchesley** [JetBrains/kotless#31]
No doubt pilot error, but...

When I use
	implementation("io.kotless", "lang", "0.1.3")
I get 
Error: Could not find or load main class io.kotless.local.MainKt

Changing to
	implementation("io.kotless", "lang-local", "0.1.3")
I get
Exception in thread "main" java.lang.IllegalStateException: System.getenv(Constants.Local.serverPort) must not be null
	at io.kotless.local.MainKt.main(Main.kt:6)
	at io.kotless.local.MainKt.main(Main.kt)

This is all with a default port number.

Thanks for any help.

**Comment by TanVD** [comment]
Could you please share `build.gradle.kts` of your project? It should work with `implementation("io.kotless", "lang", "0.1.3")`.

**Comment by svok** [comment]
I got the same behavior with Ktor 1.3.1. For proper working I had to roll back to Ktor 1.2.4.

**Comment by hchesley** [comment]
Simplest build.gradle.kts I could manage, same error. Note: just trying to get it running locally for now; will move it to AWS later.

import io.kotless.plugin.gradle.dsl.kotless

plugins {
	kotlin("jvm") version "1.3.61" apply true

	id("io.kotless") version "0.1.3" apply true
}

repositories {
	jcenter()
}

dependencies {
	implementation("io.kotless", "lang", "0.1.3")
}

kotless {
	webapp {
		lambda {
			kotless {
				packages = setOf("main")
			}
		}
	}

	extensions {
		local {
			port = 9090
		}
	}

}

**Comment by TanVD** [comment]
Well, you should not use `lang-local`, cause it will be dynamically added by gradle plugin.
As for initial error, I am unable to reproduce it. Could you please send me whole log of Gradle and, if possible, example application? 
You can contact me via email or in KotlinLang slack

**Comment by huksley** [comment]
@TanVD Hi, I am trying to use this kotless together with ktor and I am experiencing similar issue. What was the resolution for it?

**Comment by TanVD** [comment]
@huksley it really depends on the `build.gradle.kts` configuration. Most likely the problem is due to some misconfiguration. Check that you are using the latest version of Kotless and `ktor-lang` Kotless dependency instead of some Ktor engine ([see]( https://github.com/JetBrains/kotless/wiki/Getting-Started#setting-up-gradle-project)).
 
Probably I would be able to help you better if you would share your project configuration to me in Kotlin Slack or via mail :) In that case I'll be able at least to try to reproduce the problem locally

**Comment by huksley** [comment]
@TanVD Kotlin slack is manual approval? I've sent an invite request via form.

Source code is here: https://github.com/huksley/lunchtime

## When I run `./gradlew run`

```
> Task :run FAILED
Error: Could not find or load main class io.kotless.local.ktor.MainKt
Caused by: java.lang.ClassNotFoundException: io.kotless.local.ktor.MainKt
```

## When I run `./gradlew local`

```
> Task :local FAILED

> Task :run FAILED
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.base/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541)
        at java.base/java.lang.ClassLoader.getClassLoadingLock(ClassLoader.java:667)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:593)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at io.kotless.local.ktor.MainKt.main(Main.kt:13)
        at io.kotless.local.ktor.MainKt.main(Main.kt)

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':local'.
> There should be a class or object inherited from class com.amazonaws.services.lambda.runtime.RequestStreamHandler or Kotless in your app
```

**Comment by TanVD** [comment]
@huksley as far as I see the error is right :) You need to have `Kotless` inherited class and setup application in it. This is the only change between regular Ktor application and Kotless based. 
So, just add something like:
```kotlin
class Server : Kotless() {
    override fun prepare(app: Application) {
        app.main()
    }
}
```
