### ISSUE TITLE
Kotlin React integration

### ISSUE THREAD

**Issue by iurysza** [JetBrains/kotless#47]
Is it possible to serve a kotlin react app with kotless?

If so, can you please describe in broad terms what the project setup would look like?
I've checked this [jvm-js-fullstack](https://github.com/kotlin-hands-on/jvm-js-fullstack) project, but I think this is not the way to go in this case, since we're not able to relay calls to an embedded server just for serving the react app.

Thanks!

**Comment by TanVD** [comment]
Hm, probably it is possible if you don't need WebSocket support. But since I am not an expert (even a not newbie :) ) in React I'll probably have to consult with my colleagues :)
