### ISSUE TITLE
Document implicit permissions needed for 'kotless user'

### ISSUE THREAD

**Issue by AarjavP** [JetBrains/kotless#51]
I am following along the (instructions)[https://hadihariri.com/2020/05/12/from-zero-to-lamda-with-kotless/] by Hadi Hariri as mentioned in the getting started section of the project's README.md
I think for simplicity's sake he is granting admin access to the user for kotless, but I want to do a more fine tuned setup.
I do not have any experience with AWS so sorry if this is an impossible ask, but essentially what I'm looking for is something like:
- ` @Get("/hello") fun helloMsg() = "Hello World!"` endpoint needs `AWSCodeDeployRoleForLambda`
- static files usage also needs `AmazonS3FullAccess`
- DynamoDB usage also needs `AmazonDynamoDBFullAccess`

Unless I'm wrong about the permissions management feature and its doing more than just declaring what's needed in an app? The way I understand it is that the 'kotless user' which does the deployment of code and all the wiring has different set of permissions than the app itself.

**Comment by TanVD** [comment]
You are absolutely right. Application and user for deployment have differents sets of permissions.
In case of application -- Kotless grants permissions granularly. Lambdas would not have access to S3 at all, if you would not use `@S3Bucket` annotation. ApiGateway generated would have access only to s3 objects and lambdas of this specific application.

But! To perform the deployment admin permissions are necessary. To be more precise, we need a number of very different permissions -- to create lambdas, to create s3 objects, to assign IAM roles, etc., etc., etc.

So, it is easier to grant deployment user admin rights. But, if you want, you can remove this user right after the deployment was peformed. Application would work like a charm :)
