### ISSUE TITLE
Error: No certificate for domain "foo.com" found in this region

### ISSUE THREAD

**Issue by dustinconrad** [JetBrains/kotless#57]
I might be completely off base, but it seems like the ACM certificate needs to be in us-east-1?  This caught me a bit by surprise as the region specified in the terraform block was respected for everything else.

https://github.com/JetBrains/kotless/blob/ab31b2dab87f4b6263a9aa429626deef75934bd7/engine/src/main/kotlin/io/kotless/gen/factory/route53/CertificateFactory.kt#L20

**Comment by onema** [comment]
I'm not sure what the context of the CertificateFactory is, but if it is to generate an APIGateway edge-optimized domain mapping, this is related to [CloudFront requiring an ACM certificate from US-East-1](https://docs.aws.amazon.com/acm/latest/userguide/acm-regions.html) 🤷‍♂️ 
Also, see [this link](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html) for additional information.

**Comment by dustinconrad** [comment]
Okay, that is probably it then, thanks onema.

**Comment by TanVD** [comment]
Yep, it is mentioned also in [getting started](https://github.com/JetBrains/kotless/wiki/Getting-Started). Unfortunately, Kotless is unable to help in that case :(
