### ISSUE TITLE
On Windows 0.1.6 not generates aws_api_gateway_integration and aws_lambda_function resources

### ISSUE THREAD

**Issue by zaenk** [JetBrains/kotless#58]
#### Steps to reproduce

* On Windows 10
* Create new project
* Follow the Getting started guide from the README
* Run `gradlew generate`
* See the result here: https://gist.github.com/zaenk/72cc300a79bdc59051dec4bc1b8ca795#file-kotless-0-1-6-tf
* If you try to deploy it, it will fail whit error message, saying API gateway integration is missing

#### Expected outcome

* Find the expected output here: https://gist.github.com/zaenk/72cc300a79bdc59051dec4bc1b8ca795#file-kotless-fixed-tf
* Find the diff between the two files here: https://gist.github.com/zaenk/72cc300a79bdc59051dec4bc1b8ca795#file-kotless-fix-diff

#### Notes

I did some investigation, will submit a PR with a possible fix shortly.  `download_terraform` task tries to `chmod` the downloaded terraform executable, which fails on windows.

**Comment by TanVD** [comment]
PR is merged, thanks! I'll release it with `0.1.7`
