### ISSUE TITLE
Gradle build is successful even if deploy fails

### ISSUE THREAD

**Issue by v3rm0n** [JetBrains/kotless#64]
I'm using `deploy` task to release my app to production on Gitlab CI, but the pipeline is successful even if the deploy fails because when `terrafrom apply` fails it doesn't mark the task as failed.

**Comment by v3rm0n** [comment]
Opened PR https://github.com/JetBrains/kotless/pull/65

**Comment by TanVD** [comment]
Merged, thanks! Would be released with 0.1.7 :)
