### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by OrangeFlag** [JetBrains/kotless#7]
Add the ability to use env variable for lambda
It is desirable with the ability to choose different values of variables in each region

**Comment by TanVD** [comment]
Have you tried to use SSM for such purposes? I strongly think that environment variables should be avoided, if you can use SSM or other Configuration storage

**Comment by OrangeFlag** [comment]
No, I want to use different s3 bucket in different region, because they have the same namespace
Therefore, I thought that passing the bucket name through env variables is a good idea.

**Comment by TanVD** [comment]
Anyhow, I would consider usage of SSM for such purpose
