### ISSUE TITLE
Static binary resources on AWS not working properly

### ISSUE THREAD

**Issue by pjwalstrom** [JetBrains/kotless#70]
When deploying a binary static resource (such as a picture) to AWS, the resource is often not displayed in the browser. The behaviour is not consistent over browsers; sometimes the resource is not shown in Chrome, whereas Safari seems to display correctly. 

Examples:
Deployed with Kotless: https://www.waperon.org
Binary resource: https://www.waperon.org/fjell.jpg
Source-code: https://github.com/pjwalstrom/kotless-test

See also discussion at https://kotlinlang.slack.com/archives/CKS388069/p1603052191057300

Related to https://github.com/JetBrains/kotless/issues/24

**Comment by TanVD** [comment]
Fixed by @mkuzmin!)
