### ISSUE TITLE
Terraform as code

### ISSUE THREAD

**Issue by OrangeFlag** [JetBrains/kotless#8]
I think it would be interesting to have in git the generated terraform code.
Now it's difficult, because kotless-gen can clean up with all build directory
If it were in a non-erasable folder, it could be saved to git

Besides, this will allow to change the logic of the deployment to a more interesting option. To deploy you would have had to write the necessary code, generate terraform code and only after that deploy it. This will complicate the deployment a bit, but will allow better control over it and track changes in git

Also, It might be a good idea to move all the generated code to the terraform module so that the user in this folder can also describe its own resources.

**Comment by OrangeFlag** [comment]
But maybe it's a bad idea, I'm not sure
It will be tempting to change the generated code.

**Comment by TanVD** [comment]
Right now I've implemented support of extending generated terraform code with custom terraform files
